services:
  avito-web:
    build:
      context: ./web
    container_name: avito-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - avito-api

  avito-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: avito-api
    restart: unless-stopped
    shm_size: "1gb"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data